<?php

namespace doublesecretagency\sidekick\models;

use craft\base\Model;

/**
 * Class SkillResponse
 *
 * Constructs a response to a skill being run.
 */
class SkillResponse extends Model
{
    /**
     * @var bool Whether the skill function was successful.
     */
    public bool $success = false;

    /**
     * @var string Error message (relevant when `success` is false).
     */
    public string $error = 'An unknown error occurred';

    /**
     * @var string Success message (relevant when `success` is true).
     */
    public string $message = 'Skill function completed successfully.';

    /**
     * @var string|null Response generated by the skill function for delivery back to the API.
     */
    public ?string $response = null;

//    /**
//     * @inheritdoc
//     */
//    public function init(): void
//    {
//        parent::init();
//
//        // Do something here
//
//    }
}
