<?php
/**
 * Sidekick plugin for Craft CMS
 *
 * Your AI companion for rapid Craft CMS development.
 *
 * @author    Double Secret Agency
 * @link      https://plugins.doublesecretagency.com/
 * @copyright Copyright (c) 2025 Double Secret Agency
 */

namespace doublesecretagency\sidekick\models;

use craft\base\Model;

/**
 * Class SkillResponse
 *
 * Constructs a response to a skill being run.
 */
class SkillResponse extends Model
{
    /**
     * @var bool Whether the skill function was successful.
     */
    public bool $success = false;

    /**
     * @var string Simple text explaining the success or failure.
     */
    public string $message = 'An unknown error occurred';

    /**
     * @var string|null Data response generated by the skill function for delivery back to the API.
     */
    public ?string $response = null;

//    /**
//     * @inheritdoc
//     */
//    public function init(): void
//    {
//        parent::init();
//
//        // Do something here
//
//    }
}
